language: clojure
lein: lein2
sudo: false
cache:
  directories:
    - $HOME/.m2
script: lein cloverage --codecov
after_success:
  #- bash -ex bin/coveralls.sh
  - bash <(curl -s https://codecov.io/bash)
